repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black hangul_tutor
        language: system
        pass_filenames: false
        always_run: true
        args: [
          '--target-version', 'py312',
        ]

      - id: blacken-docs
        name: blacken-docs
        entry: poetry run blacken-docs
        language: system
        pass_filenames: false
        always_run: true

      - id: isort
        name: isort
        entry: poetry run isort hangul_tutor
        language: system
        pass_filenames: false
        always_run: true

      - id: mypy
        name: mypy
        entry: poetry run mypy -p hangul_tutor
        language: system
        pass_filenames: false
        always_run: true

      - id: pyright
        name: pyright
        entry: poetry run pyright hangul_tutor
        language: system
        pass_filenames: false
        always_run: true
        args: [
          --pythonpath, .venv/bin/python,
          --pythonversion, '3.12'
        ]

      - id: ruff
        name: ruff
        entry: poetry run ruff check hangul_tutor
        language: system
        pass_filenames: false
        always_run: true

      - id: pytest
        name: pytest
        entry: poetry run pytest hangul_tutor
        language: system
        pass_filenames: false
        always_run: true
