repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: poetry-check
        name: poetry check (Python configuration check)
        entry: poetry check
        language: system
        pass_filenames: false
        always_run: true
        fail_fast: true

      - id: django-check
        name: django check (Django system check)
        entry: poetry run python bin/manage.py check
        language: system
        pass_filenames: false
        always_run: true
        fail_fast: true

      - id: ruff-check
        name: ruff check (Python static analysis)
        entry: poetry run ruff check hangul_tutor
        language: system
        pass_filenames: false
        always_run: true
        args: [
          --fix,
          --show-fixes,
          --output-format=full,
        ]

      - id: isort
        name: isort (Python import sorter)
        entry: poetry run isort hangul_tutor
        language: system
        pass_filenames: false
        always_run: true

      - id: ruff-format
        name: ruff format (Python code formatter)
        entry: poetry run ruff format hangul_tutor
        language: system
        pass_filenames: false
        always_run: true

      - id: pyright
        name: pyright (Type checking)
        entry: poetry run pyright hangul_tutor
        language: system
        pass_filenames: false
        always_run: true
        args: [
          --pythonpath, .venv/bin/python,
          --pythonversion, '3.12'
        ]

      - id: pytest
        name: pytest (Unit tests)
        entry: poetry run pytest hangul_tutor
        language: system
        pass_filenames: false
        always_run: true
